### ISSUE TITLE
System Bridge 3.0.0

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#1551]
### Description

⚠️ Major breaking change. This is a  completely different application and will replace v2.x.x ⚠️

Replace the backend with a python application. Remove NodeJS as backend. Revamp Frontend and GUI to work with the new system.

## TODO

- [x] Authentication (api-key or something else)
- [x] Limit data API to implemented modules
- [x] Update on timer (after setup)
- [x] Bridges (api)
- [x] Notifications
- [x] #1604
- [x] #1578
- [x] Open Path/URL
- [x] Keyboard (https://github.com/asweigart/pyautogui ?)
- [x] Media/Filesystem (read, write, media browser integration - https://github.com/ActiveState/appdirs)
- [x] Convert numbers to numbers and None to null in JSON API output
- [x] Logging to log file
- [x] Settings
- [x] WebSocket (https://github.com/timmo001/system-bridge/blob/master/src/components/api/events/events.gateway.ts)
- [x] Settings from WebSocket
- [x] Frontend rework
- [x] GUI rework
- [x] Launch GUI (Launch from backend if GUI avaliable/enabled)
- [x] #1555
- [x] #1556
- [x] #1566
- [x] #1581
- [x] #1599
- [x] #1561
- [x] #1598
- [x] https://github.com/timmo001/system-bridge-site/issues/367
- [x] #1562
- ~~#1557 (Removed)~~

## Optional/Future

- [ ] #1554
- [ ] #1553
- [ ] #1563
- [ ] #1619
- [ ] #1620
- [ ] #1618
- [ ] #1621
- [ ] #1615
- [ ] #1614
- [ ] #1616
- [ ] #1617
- [ ] #1611
- [ ] #1612
- [ ] #1613
- [ ] #1552
- [ ] #1570
- ~~MacOS (Removed due to lack of knowledge)~~

## Packages to look at:

- https://github.com/kivy/plyer
- https://github.com/pyusb/pyusb
- https://github.com/AndreMiras/pycaw
- https://github.com/asweigart/pyautogui
- https://github.com/boppreh/keyboard
- https://github.com/boppreh/mouse
- https://github.com/gladykov/rebooter
- https://github.com/pybluez/pybluez
- https://github.com/yunstanford/pytest-sanic
- https://github.com/ActiveState/appdirs

**Comment by timmo001** [comment]
Moved from #1529

**Comment by timmo001** [comment]
Future issues opened. Closing issue and milestone. Ready to release
