### ISSUE TITLE
Media Player - Features

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#243]
# Description

There are some additional features needed to allow Home Assistant to interact with the audio/video player.

## TODO

- [x] Report playing status #244 
- [x] Player volume #246 
- [x] Seek playback control and report position #247 
- [x] Album art / video thumbnail #248 
- [x] Websocket reporting instead of using API #213 

### Future / lower priority additions:

- Audio/Video player playlist support?

## Additional

https://developers.home-assistant.io/docs/core/entity/media-player
