### ISSUE TITLE
Post home-assistant/core#107957 changes

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2899]
### Description

To be done after home-assistant/core#107957 ✅ 

- [x] home-assistant/core#112175
- [x] home-assistant/core#100055
- [x] home-assistant/core#112189
- [x] https://github.com/timmo001/system-bridge-models/pull/22
- [x] https://github.com/timmo001/system-bridge-connector/pull/13
- [x] home-assistant/core#112608
- [x] home-assistant/core#112612
- [x] home-assistant/core#103564
- [x] home-assistant/core#104095
- [x] #2900

**Comment by timmo001** [comment]
Continue in #3002
