### ISSUE TITLE
GUI migration

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2911]
### TODO

- [x] #2910
- [x] ~Check backend is running every X seconds~ (To be replaced when frontend is migrated)
- [x] ~#2912~ (To be implemented later)
  - [x] Startup
  - [x] ~Tray~ (To be implemented in new frontend)
- [x] Check windows sensors runs
