### ISSUE TITLE
4.1.0 Checklist

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2956]
### TODO

- [x] #2946 
- [x] Update all packages to latest
- [x] Test notifications - c9ed48c052b4255aea369aff98a6c2c1f82825b3
- [x] HA integration
- [x] Test windows
- [x] https://github.com/timmo001/system-bridge-shared/pull/41 https://github.com/timmo001/system-bridge-shared/pull/42
- [x] Test linux
