### ISSUE TITLE
Home Assistant todo list

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#3002]
Continuation of #2899 

- [x] #3008 
- [x] home-assistant/core#112206
- [x] https://github.com/home-assistant/core/pull/114896
- [ ] [HA Integration - Tests](https://github.com/timmo001/core/tree/systembridge-tests-2/tests/components/system_bridge)
- [ ] HA Integration - Icon translations
- [ ] HA Integration - Display sensors (Pixel clock etc. disabled by default)
- [ ] HA Integration - Per CPU sensors (Disabled by default)
- [ ] HA Integration - Use latest version url from System module
